version: '3'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - webapp_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: task26_blog
      MYSQL_ROOT_USER: root
    ports:
      - "3307:3306"
    networks:
      - webapp_network

networks:
  webapp_network:

