version: '3'
services:
  db:
    image: mysql:8.0.34
    container_name: ITbaza_web
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: itbaza
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: rootroot
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ITbaza_back
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: 
      - db
volumes:
  data: